#!/bin/bash

###############################################################################
# OPENLOOP AUTONOMOUS CONTROL CENTER
# Master orchestrator for self-healing system
# Run: bash scripts/control-center.sh [command]
###############################################################################

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_DIR="$REPO_ROOT/app"
CONTROL_LOG="/tmp/openloop-control-$(date +%Y%m%d-%H%M%S).log"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m'

###############################################################################
# LOGGING
###############################################################################

log_start() {
  echo -e "${CYAN}[$(date '+%H:%M:%S')] ▶ $1${NC}" | tee -a "$CONTROL_LOG"
}

log_success() {
  echo -e "${GREEN}[$(date '+%H:%M:%S')] ✓ $1${NC}" | tee -a "$CONTROL_LOG"
}

log_error() {
  echo -e "${RED}[$(date '+%H:%M:%S')] ✗ $1${NC}" | tee -a "$CONTROL_LOG"
}

log_info() {
  echo -e "${BLUE}[$(date '+%H:%M:%S')] ℹ $1${NC}" | tee -a "$CONTROL_LOG"
}

log_warning() {
  echo -e "${YELLOW}[$(date '+%H:%M:%S')] ⚠ $1${NC}" | tee -a "$CONTROL_LOG"
}

###############################################################################
# COMMANDS
###############################################################################

cmd_diagnose() {
  log_start "Running full system diagnostic..."
  echo ""
  
  # 1. Build status
  log_info "Checking TypeScript compilation..."
  cd "$APP_DIR"
  if npx tsc --noEmit >/dev/null 2>&1; then
    log_success "TypeScript check passed"
  else
    log_error "TypeScript errors detected"
    npx tsc --noEmit 2>&1 | head -10
    return 1
  fi
  
  # 2. Dependencies
  log_info "Checking dependencies..."
  if npm audit --json 2>/dev/null | jq -e '.metadata.vulnerabilities.total <= 1' >/dev/null 2>&1; then
    log_success "Dependencies are secure"
  else
    log_warning "Security vulnerabilities found"
  fi
  
  # 3. Build
  log_info "Testing Next.js build..."
  cd "$APP_DIR"
  # Set minimal DATABASE_URL for build time if not set
  export DATABASE_URL="${DATABASE_URL:-postgresql://localhost/openloop_build}"
  if timeout 120 npm run build >/dev/null 2>&1; then
    log_success "Build successful"
  else
    log_error "Build failed"
    return 1
  fi
  
  # 4. Routes
  log_info "Validating API routes..."
  invalid=$(find "$APP_DIR/src/app/api" -name "route.ts" | while read f; do
    grep "export async function" "$f" | grep -v "GET\|POST\|PUT\|DELETE\|PATCH" | wc -l
  done | awk '{s+=$1} END {print s}')
  
  if [ "${invalid:-0}" -eq 0 ]; then
    log_success "All API routes valid"
  else
    log_error "$invalid invalid route exports found"
    return 1
  fi
  
  echo ""
  log_success "Diagnostic complete - system healthy"
  return 0
}

cmd_repair() {
  log_start "Running auto-repair..."
  echo ""
  
  # 1. Fix duplicates
  log_info "Fixing duplicate declarations..."
  find "$APP_DIR/src/app/api" -name "*.ts" 2>/dev/null | while read -r file; do
    if grep -c "const sort = " "$file" 2>/dev/null | grep -q "^[2-9]"; then
      awk '!seen[$0]++' "$file" > "$file.tmp"
      mv "$file.tmp" "$file"
      log_success "Fixed duplicates in $(basename $file)"
    fi
  done
  
  # 2. Fix dependencies
  log_info "Installing dependencies..."
  cd "$APP_DIR"
  if npm ci >/dev/null 2>&1; then
    log_success "Dependencies installed"
  else
    log_error "Dependency installation failed"
    return 1
  fi
  
  # 3. Audit fix
  log_info "Fixing vulnerabilities..."
  npm audit fix --force >/dev/null 2>&1 || true
  log_success "Security audit complete"
  
  # 4. Git commit
  log_info "Committing fixes..."
  cd "$REPO_ROOT"
  git add -A
  if git diff --cached --quiet; then
    log_info "No changes to commit"
  else
    if git commit -m "Auto-repair: Fix detected issues

- Fixed duplicate declarations
- Installed/updated dependencies
- Applied security fixes
- Auto-generated by control center" >/dev/null 2>&1; then
      log_success "Fixes committed"
    else
      log_warning "No new commits (working tree clean)"
    fi
  fi
  
  echo ""
  log_success "Repair complete"
  return 0
}

cmd_deploy() {
  log_start "Preparing deployment..."
  echo ""
  
  # Check status
  cmd_diagnose || {
    log_error "Cannot deploy - system has errors"
    return 1
  }
  
  echo ""
  log_start "Pushing to GitHub..."
  
  cd "$REPO_ROOT"
  if git push origin main 2>&1 | grep -q "main -> main"; then
    log_success "Pushed to GitHub"
  else
    log_warning "Push rejected - pulling first"
    git pull --rebase origin main >/dev/null 2>&1
    git push origin main >/dev/null 2>&1 || {
      log_error "Push failed - check git credentials"
      return 1
    }
    log_success "Pushed to GitHub (after rebase)"
  fi
  
  echo ""
  log_info "GitHub Actions will now:"
  log_info "  1. Run full diagnostic"
  log_info "  2. Auto-fix any issues"
  log_info "  3. Validate build"
  log_info "  4. Check deployment readiness"
  log_info "  5. Report status"
  
  echo ""
  log_info "View progress: https://github.com/disputestrike/OpenLoop/actions"
  log_success "Deployment initiated"
  return 0
}

cmd_monitor() {
  log_start "Starting real-time monitoring..."
  echo ""
  
  while true; do
    clear
    echo -e "${MAGENTA}"
    echo "╔════════════════════════════════════════════════════════════╗"
    echo "║        OPENLOOP CONTROL CENTER - REAL-TIME MONITOR        ║"
    echo "║                                                            ║"
    echo "║  Autonomous Self-Healing System                           ║"
    echo "╚════════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    
    # Quick status
    printf "  %-40s " "Build status"
    if cd "$APP_DIR" && export DATABASE_URL="${DATABASE_URL:-postgresql://localhost/openloop_build}" && timeout 10 npm run build >/dev/null 2>&1; then
      echo -e "${GREEN}✓ PASS${NC}"
    else
      echo -e "${RED}✗ FAIL${NC}"
    fi
    
    printf "  %-40s " "TypeScript"
    if cd "$APP_DIR" && npx tsc --noEmit >/dev/null 2>&1; then
      echo -e "${GREEN}✓ PASS${NC}"
    else
      echo -e "${RED}✗ FAIL${NC}"
    fi
    
    printf "  %-40s " "Dependencies"
    if cd "$APP_DIR" && npm audit --json 2>/dev/null | jq -e '.metadata.vulnerabilities.total <= 1' >/dev/null 2>&1; then
      echo -e "${GREEN}✓ SECURE${NC}"
    else
      echo -e "${YELLOW}⚠ ISSUES${NC}"
    fi
    
    printf "  %-40s " "API routes"
    invalid=$(find "$APP_DIR/src/app/api" -name "route.ts" | while read f; do
      grep "export async function" "$f" | grep -v "GET\|POST\|PUT\|DELETE\|PATCH" | wc -l
    done | awk '{s+=$1} END {print s}')
    if [ "${invalid:-0}" -eq 0 ]; then
      echo -e "${GREEN}✓ VALID${NC}"
    else
      echo -e "${RED}✗ $invalid INVALID${NC}"
    fi
    
    echo ""
    echo -e "${BLUE}Last update: $(date '+%H:%M:%S')${NC}"
    echo -e "${BLUE}Log: $CONTROL_LOG${NC}"
    echo ""
    echo "Commands:"
    echo "  [D] Diagnose  [R] Repair  [P] Deploy  [Q] Quit"
    echo ""
    read -p "Enter command: " -t 30 cmd
    
    case $cmd in
      D|d) cmd_diagnose ;;
      R|r) cmd_repair ;;
      P|p) cmd_deploy ;;
      Q|q) log_info "Monitoring stopped"; break ;;
      *) ;; # Timeout or invalid - continue monitoring
    esac
  done
}

cmd_health() {
  log_start "System health check"
  echo ""
  
  score=0
  max=100
  
  # Build
  printf "  Build: "
  if cd "$APP_DIR" && export DATABASE_URL="${DATABASE_URL:-postgresql://localhost/openloop_build}" && timeout 60 npm run build >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC}"; score=$((score + 25))
  else
    echo -e "${RED}✗${NC}"
  fi
  
  # TypeScript
  printf "  TypeScript: "
  if cd "$APP_DIR" && npx tsc --noEmit >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC}"; score=$((score + 25))
  else
    echo -e "${RED}✗${NC}"
  fi
  
  # Dependencies
  printf "  Dependencies: "
  if cd "$APP_DIR" && npm audit --json 2>/dev/null | jq -e '.metadata.vulnerabilities.total <= 1' >/dev/null 2>&1; then
    echo -e "${GREEN}✓${NC}"; score=$((score + 25))
  else
    echo -e "${YELLOW}⚠${NC}"
  fi
  
  # Routes
  printf "  Routes: "
  invalid=$(find "$APP_DIR/src/app/api" -name "route.ts" | while read f; do
    grep "export async function" "$f" | grep -v "GET\|POST\|PUT\|DELETE\|PATCH" | wc -l
  done | awk '{s+=$1} END {print s}')
  if [ "${invalid:-0}" -eq 0 ]; then
    echo -e "${GREEN}✓${NC}"; score=$((score + 25))
  else
    echo -e "${RED}✗${NC}"
  fi
  
  echo ""
  echo "Health Score: $score/$max"
  
  if [ $score -eq 100 ]; then
    log_success "System is HEALTHY"
  elif [ $score -ge 75 ]; then
    log_warning "System is DEGRADED - issues detected"
  else
    log_error "System is CRITICAL - immediate repair needed"
  fi
  
  return 0
}

###############################################################################
# MAIN
###############################################################################

if [ $# -eq 0 ]; then
  echo "OpenLoop Autonomous Control Center"
  echo ""
  echo "Usage: bash scripts/control-center.sh [command]"
  echo ""
  echo "Commands:"
  echo "  diagnose  - Full system diagnostic"
  echo "  repair    - Auto-fix detected issues"
  echo "  deploy    - Test, fix, and deploy to GitHub"
  echo "  monitor   - Real-time monitoring dashboard"
  echo "  health    - Quick health check"
  echo ""
  echo "Examples:"
  echo "  bash scripts/control-center.sh diagnose"
  echo "  bash scripts/control-center.sh repair"
  echo "  bash scripts/control-center.sh deploy"
  echo ""
  exit 0
fi

case "$1" in
  diagnose) cmd_diagnose ;;
  repair) cmd_repair ;;
  deploy) cmd_deploy ;;
  monitor) cmd_monitor ;;
  health) cmd_health ;;
  *)
    echo "Unknown command: $1"
    exit 1
    ;;
esac

log_info "Command complete - log saved to $CONTROL_LOG"
